### PR TITLE
Improve logos in the website listing page and Firefox CSS fixes

### PR DESCRIPTION
**Pull request by datkat21**
I tried to make two separate PRs but i messed up lol 

## first half

Fixes CSS problems in Firefox, including but not limited to:

- Fix the typewriter on the landing page looking horrible (wraps to new line)
- Makes scrollbar invisible in settings page
- `<a>` tags in the settings page looking strange
- Fonts in buttons/inputs are incorrect

---

## second half

I hand-redid some of the odd-looking logos in Figma using a neomorphic-ish style, hope it works here :D

### CODE REVIEW

**Comment by datkat21** [comment]
Just noticed the Snap vector I used looks really odd :(

**Comment by not-amplify** [comment]
@datkat21 do you have a discord where I can talk over changes with you?

**Comment by datkat21** [comment]
It's on the README on my profile if you need it.

**Comment by not-amplify** [comment]
> It's `kat21` if you need it.

I will dm you.

**Comment by crllect** [comment]
not heard anything abt this in a min

**Pull request closed without merging**
